---
type: showroom

# Set the left column width to 30%
default_width: 30
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
    - name: '>_Terminal'
      path: /wetty
      port: 443
      secondary_name: '>_Terminal-02'
      secondary_path: /terminal2
      secondary_port: 443
    - name: 'Cockpit'
      url: "{{ workshop_cockpit_url }}"
